export const imageList = [
  {
    id: 1,
    url: 'https://fakeimg.pl/250x250/',
    tags: [],
    group: '全部',
  },
  {
    id: 2,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 3,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn'],
    group: '全部',
  },
  {
    id: 4,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 5,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 6,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 7,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 8,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 9,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 10,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 11,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 12,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 13,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 14,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
  {
    id: 15,
    url: 'https://fakeimg.pl/250x250/',
    tags: ['abcdefghijklmn', 'hijklmnopq'],
    group: '全部',
  },
]
